[colors.primary]
background = '#FFFFFF'
foreground = '#1F2328'

[colors.cursor]
text = "#FFFFFF"
cursor = "#1F2328"

[colors.normal]
black = "#24292F"
red = "#CF222E"
green = "#116329"
yellow = "#4D2D00"
blue = "#0969DA"
magenta = "#8250DF"
cyan = "#1B7C83"
white = "#6E7781"

[colors.bright]
black = "#57606A"
red = "#A40E26"
green = "#1A7F37"
yellow = "#633C01"
blue = "#218BFF"
magenta = "#8250DF"
cyan = "#1B7C83"
white = "#6E7781"
