theme = "rose_pine_dawn"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-s = ":w"
Cmd-s = ":w"
g = { a = "code_action" }
space = { q = { a = ":q" } }
"$" = "goto_line_end"
"_" = "goto_line_start"
G = "goto_last_line"
C-h = "goto_previous_buffer"
C-l = "goto_next_buffer"
