return {
  {
    "rose-pine/neovim",
    name = "rose-pine",
    opts = {
      styles = {
        italic = false,
      },
      variant = "auto",
      highlight_groups = {
        EndOfBuffer = { fg = "base" },
        Constant = { fg = "rose" },
        Number = { fg = "rose" },
        ["@variable.member"] = { fg = "text" },
        ["@constant"] = { fg = "foam" },
        ["@constant.builtin"] = { fg = "rose", bold = true },
        ["@constant.macro"] = { fg = "foam" },
        CurSearch = { fg = "base", bg = "leaf", inherit = false },
        Search = { fg = "text", bg = "leaf", blend = 20, inherit = false },

        -- fff.nvim UI
        FFFBorder = { fg = "muted" },
        FFFNormal = { bg = "base" },
        FFFCursor = { bg = "overlay" },
        FFFMatched = { fg = "base", bg = "gold", inherit = false },
        FFFTitle = { fg = "foam", bold = true },
        FFFPrompt = { fg = "gold" },
        FFFActiveFile = { bg = "overlay" },
        FFFFrequency = { fg = "gold" },
        FFFDebug = { fg = "muted" },
        FFFComboHeader = { fg = "gold", bold = true },
        FFFScrollbar = { fg = "muted" },
        FFFDirectoryPath = { fg = "muted" },
        -- fff.nvim selection
        FFFSelected = { bg = "overlay" },
        FFFSelectedActive = { bg = "surface", bold = true },
        FFFGitStaged = { fg = "iris" },
        FFFGitModified = { fg = "rose" },
        FFFGitDeleted = { fg = "love" },
        FFFGitRenamed = { fg = "pine" },
        FFFGitUntracked = { fg = "subtle" },
        FFFGitIgnored = { fg = "muted" },
        FFFGitSignStaged = { fg = "iris" },
        FFFGitSignModified = { fg = "rose" },
        FFFGitSignDeleted = { fg = "love" },
        FFFGitSignRenamed = { fg = "pine" },
        FFFGitSignUntracked = { fg = "subtle" },
        FFFGitSignIgnored = { fg = "muted" },
        FFFGitSignStagedSelected = { fg = "iris", bg = "overlay" },
        FFFGitSignModifiedSelected = { fg = "rose", bg = "overlay" },
        FFFGitSignDeletedSelected = { fg = "love", bg = "overlay" },
        FFFGitSignRenamedSelected = { fg = "pine", bg = "overlay" },
        FFFGitSignUntrackedSelected = { fg = "subtle", bg = "overlay" },
        FFFGitSignIgnoredSelected = { fg = "muted", bg = "overlay" },
      },
    },
  },
  { "folke/tokyonight.nvim", enabled = false },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "rose-pine",
    },
  },
}
