add_newline = false

[character]
success_symbol = "[Î»](bold green)"

[package]
disabled = true

[docker_context]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[nix_shell]
style = "bold blue"
