#!/usr/bin/env bash
set -euo pipefail

tailscale_status="$(sudo tailscale status --json 2>/dev/null || true)"
if jq -e '.BackendState == "Running"' >/dev/null <<<"$tailscale_status"; then
  sudo tailscale logout
fi
