gui:
  nerdFontsVersion: "3"
  expandFocusedSidePanel: true
  showBottomLine: false
  filterMode: "fuzzy"
  commandLogSize: 3
  theme:
    activeBorderColor:
      - "#7287fd"
      - bold
    inactiveBorderColor:
      - "#6c6f85"
    optionsTextColor:
      - "#1e66f5"
    selectedLineBgColor:
      - "#ccd0da"
    cherryPickedCommitBgColor:
      - "#bcc0cc"
    cherryPickedCommitFgColor:
      - "#7287fd"
    unstagedChangesColor:
      - "#d20f39"
    defaultFgColor:
      - "#4c4f69"
    searchingActiveBorderColor:
      - "#df8e1d"

  authorColors:
    "*": "#7287fd"
git:
  overrideGpg: true
  commitPrefixes:
    "avatar-backend":
      pattern: "(ST-\\d+).+"
      replace: "$1: "
os:
  editPreset: "nvim"
